version: "3.8"

services:
  fractile:
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - REDIS_ENABLED=1
    build:
      context: .
      args:
        - PROJECT_ID=fractile
    ports:
      - "8000:80"
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:
  redis_data:
