version: "3.8"

services:
  fractile:
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    image: fractile:dev
    ports:
      - "8000:80"
